### ISSUE TITLE
Possibility to like after logout

### ISSUE THREAD

**Issue by ghost** [Cu8eeeR/MyBB_Thank-you-like-plugin#109] opened 2016-07-25 04:02 UTC
You can like as an unexisting user.

![image](https://cloud.githubusercontent.com/assets/4917449/17090059/45ab548c-5235-11e6-981e-8961dccc0e46.png)

Login. Open thread in two browser tabs. Logout through one tab. Like the message throught another tab. You will get an unexisting like. How to fix it?

I guess this problem appears because plugin detects user id when page is loading and do not check it during the "like" action.

**Comment by Cu8eR** [comment] 2016-07-31 10:36
@CMTV - I can confirm that... thank you for reporting this

**Comment by SvePu** [comment] 2017-01-06 13:33
looks like a temporary mistake.. after reloading the given thank isn't in tyl list 

https://youtu.be/g6RlhrsIiBE

**Comment by Cu8eeeR** [comment] 2017-01-06 14:31
@SvePu - yes, I can confirm this. The thx/like is not added into list. Is there any easy solution which check user log in/out state? If not, feel free to close this. Thank you

**Comment by SvePu** [comment] 2017-01-07 14:01
I've searched for a quick solution, but it seems to be a difficult fix.

We will need an Ajax logged in check for this, but I don't know how we can realize this - maybe with a cookie check.

**Comment by Cu8eeeR** [comment] 2017-01-07 14:11
@SvePu - OK, I am closing this then. :) Thank you for your time!

**Closed by Cu8eeeR** 2017-01-07 14:11 UTC
Labels: bug, question
